/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.banDAO;
import DAO.hoaDonDAO;
import DAO.sanphamDAO;
import Entity.Ban;
import Entity.DsOrder;
import Entity.HoaDon;
import Entity.SanPham;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author nguye
 */
public class JPchart extends javax.swing.JPanel {

    /**
     * Creates new form JPchart
     */
    public JPchart() {
        initComponents();
        hoaDon();
        Mon();
    }
    hoaDonDAO hdDAO = new hoaDonDAO();
    banDAO banDAO = new banDAO();
    public void hoaDon() {
        List<HoaDon> listHD = hdDAO.getDoanhThuTheoNgay();       
        SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
        if (listHD.size() > 0) {
            DefaultCategoryDataset data = new DefaultCategoryDataset();
            for (HoaDon x : listHD) {
                data.addValue(x.getTongTien(), "Tổng Tiền", sf.format(x.getGioDen()));               
            }
            jPanel1.removeAll();
            JFreeChart chart = ChartFactory.createBarChart("THỐNG KÊ HÓA ĐƠN THEO NGÀY", 
                    "Ngày", "Tổng tiền", data, PlotOrientation.VERTICAL, true, true, true);
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(jPanel1.getWidth(),jPanel1.getHeight()));
            
            jPanel1.setLayout(new java.awt.BorderLayout());            
            jPanel1.add(chartPanel, BorderLayout.CENTER);
            jPanel1.validate();
            jPanel1.updateUI();
        }
    }
    
    sanphamDAO spDAO = new sanphamDAO();
    public void Mon() {           
        List<SanPham> tableSP = spDAO.thongKeMon();       
        SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
        if (tableSP.size() > 0) {
            DefaultCategoryDataset data = new DefaultCategoryDataset();
            for (SanPham sp : tableSP) {
                ArrayList<DsOrder> ct = spDAO.bieuDo(sp.getMaMon());
                if (ct.size() > 0) {
                    int soluong = 0;
                    for (DsOrder a : ct) {
                        soluong += a.getSoLuong();
                    }
                    System.out.println(soluong);
                    data.addValue(soluong, "Số lượng", sp.getTenMon());
                }               
            }
            jPanel2.removeAll();
            JFreeChart chart = ChartFactory.createBarChart("THỐNG KÊ MÓN THEO SỐ LƯỢNG", 
                    "TÊN SẢN PHẨM", "SỐ LƯỢNG", data, PlotOrientation.VERTICAL, true, true, true);
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(jPanel2.getWidth(),jPanel2.getHeight()));
            
            jPanel2.setLayout(new java.awt.BorderLayout());            
            jPanel2.add(chartPanel, BorderLayout.CENTER);
            jPanel2.validate();
            jPanel2.updateUI();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHoaDon = new javax.swing.JPanel();
        jpMon = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jpHoaDon.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jpMonLayout = new javax.swing.GroupLayout(jpMon);
        jpMon.setLayout(jpMonLayout);
        jpMonLayout.setHorizontalGroup(
            jpMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpMonLayout.setVerticalGroup(
            jpMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFmain.main.reloadPanel(4);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpHoaDon;
    private javax.swing.JPanel jpMon;
    // End of variables declaration//GEN-END:variables
}
